### ISSUE TITLE
SKR Mini E3 USB Connection

### ISSUE THREAD

**Issue by ilakuli** [bigtreetech/BIGTREETECH-SKR-mini-E3-#2] opened 2019-07-08 06:57 UTC
Hello,

My SKR Mini E3 keeps disconnecting from any USB Device after about 15 seconds. Tested on Windows PC and Octoprint. In Windows, the board shows up and connects normally but after 15 seconds it just disconnects. In Octoprint the same thing happens. Firmware was configured and compiled according to the List provided on Github. Have noticed the issue with conflicting serial port information and tried both ways. Nothing solved the issue. Any help would be appreciated.

Thanks.

**Comment by vyruz1986** [comment] 2019-07-08 19:52
I can confirm the same behavior on my E3 Mini board with the latest build from Marlin directly (at commit 2b1c2a0db)

**Comment by Msq001** [comment] 2019-07-09 01:15
I will test it

**Comment by Msq001** [comment] 2019-07-09 02:17
Can you provide firmware. bin file? I tested the latest version of marlin, no such behavior, and I uploaded a workable firmware. bin in [here](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3-/tree/master/firmware), you can try to use this to see if it works properly.

**Comment by ilakuli** [comment] 2019-07-09 04:21
[Firmware.zip](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3-/files/3371168/Firmware.zip)
attached is the firmware.bin.

I will test your firmware but I cannot use it permanenlty since my Ender 3 hast a different hotend and auto bed leveling.

Thanks,

**Comment by ilakuli** [comment] 2019-07-09 04:33
Your firmware resolved the issue. Can you provide the source code so I can add auto bed level and compile myself?

**Comment by Msq001** [comment] 2019-07-09 04:39
this firmware.bin is compiled from old version Marlin, and the source code have be replaced by new verison,  this issue maybe the Marlin's bug,  I will locate and fix it as soon as possible,  when I fix this, I will tell you and  upload the workable source code in here.

**Comment by vyruz1986** [comment] 2019-07-09 05:43
Could everyone please state which commit of marlin they are building and
testing?

I have this issue with commit 2b1c2a0db

Will try later today with the bin file provided by Msq001, thanks

**Comment by vyruz1986** [comment] 2019-07-09 22:02
Here's a zip (with firmware.bin , github doesn't allow *.bin uploads) which demonstrates the problem.
[firmware.zip](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3-/files/3374956/firmware.zip)

It was compiled by setting `#define SERIAL_PORT_2 -1` and with marlin at commit ab99a807

**Comment by Msq001** [comment] 2019-07-10 02:42
hi~  I have update source code, LCD12864 is ok, usb connect to printrun is ok

**Comment by Msq001** [comment] 2019-07-10 02:45
It's  just download form Latest version https://github.com/MarlinFirmware/Marlin/commit/a23021b823477b907f8b5e658afc3bbb3165be31

**Comment by vyruz1986** [comment] 2019-07-10 06:34
Below are 2 pictures comparing `configuration.h` and `configuration_adv.h` between the source code in this repository(https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3-/tree/2a167ef96c9170c63288a3c1d69b6dea9d913506/firmware/Marlin-2.0.x-SKR-Mini-E3), and MarlinFirmware/Marlin@a23021b , as you can see there are way more changes than what you currently have described in the instructions on how to flash Marlin. Likely if we apply all these changes to the latest Marlin sources, it will work as well. I'll give that a try tonight and report back here.
**Configuration_adv.h**
![2019-07-10 08_31_04-WinMerge -  Configuration_adv h x 2](https://user-images.githubusercontent.com/3620147/60945902-1b458300-a2ed-11e9-8968-4005f92ecc2b.png)

**Configuration.h**
![2019-07-10 08_30_11-WinMerge -  Configuration h x 2](https://user-images.githubusercontent.com/3620147/60945913-20a2cd80-a2ed-11e9-800f-24c67f670afe.png)

**Comment by vyruz1986** [comment] 2019-07-10 20:41
Ok so after testing, I've done the following and have a completely working Ender 3 with the BBT SKR E3 Mini board.

1. Clone the latest version of Marlin (I used MarlinFirmware/Marlin@4e479caf61fde35121351e33276aed673a365b7f)
2. In the repo you just cloned, copy the contents of `config\examples\Creality\Ender-3\` to `Marlin`
3. Make the changes described below to `Configuration.h` and `Configuration_adv.h`

### Configuration.h

```c++
#define STRING_CONFIG_H_AUTHOR "(none, default config)" // Who made the changes.
#define SERIAL_PORT 2
#define SERIAL_PORT_2 -1
  #define MOTHERBOARD BOARD_BIGTREE_SKR_MINI_E3
#define X_DRIVER_TYPE  TMC2209
#define Y_DRIVER_TYPE  TMC2209
#define Z_DRIVER_TYPE  TMC2209
#define E0_DRIVER_TYPE TMC2209
```

### Configuration_adv.h

```c++
  #define  Y_SLAVE_ADDRESS 1
  #define  Z_SLAVE_ADDRESS 2
  #define E0_SLAVE_ADDRESS 3
```

This works for my printer.

**Comment by vyruz1986** [comment] 2019-07-10 21:03
Apparently I cheered too early :) The control knob still isn't working. Printing over USB works fine, but pressing the control button causes the board to freeze up :(

**Comment by Msq001** [comment] 2019-07-11 01:11
> Apparently I cheered too early :) The control knob still isn't working. Printing over USB works fine, but pressing the control button causes the board to freeze up :(
> 
> Edit: Also the USB connection is still dropping after ~15 seconds, so this specific issue isn't really fixed it seems.

this issue please comment out `#define SPEAKER` in configuration.h file

**Comment by Msq001** [comment] 2019-07-11 01:12
and I wil update your feedback in readme.md,  thanks for your feedback !

**Comment by vyruz1986** [comment] 2019-07-12 08:11
Control knob issue was fixed by commenting out `#define SPEAKER` as suggested by @Msq001 , thanks!

**Comment by Xenon-2510** [comment] 2019-07-14 05:51
Any update on this issue? I have got the board up and running but have an issue with the X axis stepper driver and cannot debug as the serial connection doesn't work.

**Comment by Msq001** [comment] 2019-07-18 01:41
> Any update on this issue? I have got the board up and running but have an issue with the X axis stepper driver and cannot debug as the serial connection doesn't work.

Have you installed Maple USB port driver on your computer? Can you debug with this [firmware. bin](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3-/blob/master/firmware/firmware.bin)

**Comment by Xenon-2510** [comment] 2019-07-18 05:55
I will check this firmware out later today, I have installed the Maple driver on my pc but I am also trying to use Rpi3 with Octoprint. I will feedback the outcome.

**Comment by Xenon-2510** [comment] 2019-07-18 19:05
Hi,

So i tried the firmware you suggested and unfortunately it did not work, I then tried a firmware that I was sent through facebook earlier this week by Zyfio (see attached) this worked fine with the serial connection both from my PC using pronterface and my Rpi3 using Octoprint. So i know that the board works and that it is a firmware issue, I have attached the working firmware for you to try but I am afraid I do not have the source.

I am hoping that this is of some use, please let me know if there is anything else that I can do to support.

[firmware_working_serial.zip](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3-/files/3408044/firmware_working_serial.zip)

**Comment by Msq001** [comment] 2019-07-19 05:43
Hi， Even if you updated the firmware. bin that we have compiled here, the serial port is still unrecognizable?

**Comment by Msq001** [comment] 2019-07-19 08:49
SO SORRY for this issue, USB Serial can't recognize or unstable because of: USB slave needs to connect a pull-up resistor to VCC in D + to tell USB host it's own device type, we use a P-MOS to control whether the 1.5k resistance is pulled up or not, and the GPIO of P-MOS should "output" a stable low level, but It was "input" state before, so the USB device could not recognize or be unstable.
I have updated the firmware.bin and source code now, It should workable now

**Comment by nicstoun** [comment] 2019-07-19 13:41
Hi, i think soon buy this board ..i track this issues ,still board don't have stable firmware for everyday use ? 

Regards

**Comment by Msq001** [comment] 2019-07-19 13:48
the SD card print, and usb serial is ok now in my tested,  but I need more feedback, this source code and firmware.bin should workable and I have Creat a PR to fix this issue in Marlin master branch https://github.com/MarlinFirmware/Marlin/pull/14679

**Comment by nicstoun** [comment] 2019-07-19 13:55
> the SD card print, and usb serial is ok now in my tested, but I need more feedback, this source code and firmware.bin should workable and I have Creat a PR to fix this issue in Marlin master branch [MarlinFirmware/Marlin#14679](https://github.com/MarlinFirmware/Marlin/pull/14679)

Ok, for that i see only usb have some issues now , if flash firmware provided  later i get board all be fine right ?

**Comment by Xenon-2510** [comment] 2019-07-19 13:55
I have tried the source firmware this afternoon, seem to be getting inconsistent E1 Thermal runaway issues on boot. Do you need to add in a grace period for this board?

**Comment by Msq001** [comment] 2019-07-19 14:01
@Xenon-2510 This seems to happen only when you connect to USB CDC serial at startup, right? If wait  4-5s for motherboard to startup completed, then connecting USB CDC Serial is normal ?

**Comment by Msq001** [comment] 2019-07-19 14:02
> > the SD card print, and usb serial is ok now in my tested, but I need more feedback, this source code and firmware.bin should workable and I have Creat a PR to fix this issue in Marlin master branch [MarlinFirmware/Marlin#14679](https://github.com/MarlinFirmware/Marlin/pull/14679)
> 
> Ok, for that i see only usb have some issues now , if flash firmware provided later i get board all be fine right ?

yes, It should be fine.

**Comment by Xenon-2510** [comment] 2019-07-19 16:20
@Msq001 - yes, it seems to only do it when the printer is turned on with the USB plugged in. Is there anyway this can be rectified as this didn't happen with the stock board? I like to leave Octoprint connected so I can remotely turn the print on and start a print from the Web interface.

**Comment by vyruz1986** [comment] 2019-07-19 23:03
I tried building the latest bigtreetech/Marlin repository, and can confirm the USB issue is fixed 👍 
Thanks BTT!

**Comment by Msq001** [comment] 2019-07-20 07:57
@Xenon-2510  Please wait 4-5s, after motherboard startup successed, then connect USB CDC Sereial will be ok,  if you don't want to wait,  Please uncomment this
`#define BOGUS_TEMPERATURE_FAILSAFE_OVERRIDE ` in here, 
 https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3-/blob/1016c47352a5a30e4ea25dda2652418618295655/firmware/Marlin-2.0.x-SKR-Mini-E3/Marlin/src/pins/pins_BIGTREE_SKR_MINI_E3.h#L35
this is just a temporary solution.
I will continue to debug this issue, and when I find the final solution, I will update it.

**Comment by Msq001** [comment] 2019-07-20 07:58
@vyruz1986 Thanks for your feedback and patience！

**Comment by nicstoun** [comment] 2019-07-20 18:30
> > > the SD card print, and usb serial is ok now in my tested, but I need more feedback, this source code and firmware.bin should workable and I have Creat a PR to fix this issue in Marlin master branch [MarlinFirmware/Marlin#14679](https://github.com/MarlinFirmware/Marlin/pull/14679)
> > 
> > 
> > Ok, for that i see only usb have some issues now , if flash firmware provided later i get board all be fine right ?
> 
> yes, It should be fine.
Can you open theme to explain in details all options for this board. I read for DIAG   instead of Endstop,
 blocking rotation detection  ,that sound interesting but not find info in manual. 
Thank you!

**Comment by ilakuli** [comment] 2019-07-23 05:37
Just to give some Feedback: My Mini E3 is now fully running with working USB Connection so Issue solved. Let me know whether I should close this issue or keep it open.

**Comment by nicstoun** [comment] 2019-07-24 10:16
What about Eeprom settings i read this chip not support this options ? How safe calibrated settings ?

**Comment by Msq001** [comment] 2019-07-24 10:23
it can be saved in SD card file  "eeprom.dat".

**Comment by nicstoun** [comment] 2019-07-24 10:24
> it can be saved in SD card file "eeprom.dat".

Ok, so that is solution now

**Comment by Msq001** [comment] 2019-07-24 10:31
yeah. we are considering to modify stm32f103rc to stm32f103re. it have 512KB flash. can to emulation eeprom.  but not confirm yet

**Comment by nicstoun** [comment] 2019-07-24 10:52
> yeah. we are considering to modify stm32f103rc to stm32f103re. it have 512KB flash. can to emulation eeprom. but not confirm yet

Good to know , hope this happened soon :)

**Comment by reloxx13** [comment] 2019-07-31 23:40
dont close this if its not fixed!

a workaround is not a fix!

**Comment by reloxx13** [comment] 2019-08-02 23:09
@bigtreetech pls reopen

**Comment by thomasgerman** [comment] 2019-08-12 19:03
why can not I connect the board to usb?  I loaded the last marlin, when I connect the cable hangs up the board and the hotend fan whistles.  where is the problem?

**Comment by mejtoogood** [comment] 2019-08-17 13:04
Board still gives thermal runaway error when USB connected at boot. Not prepared to use workaround which degrades safety. Fix was in pipeline 24 days ago, what is status?

**Comment by bigtreetech** [comment] 2019-08-22 07:15
look here https://github.com/MarlinFirmware/Marlin/pull/15026, we have fixed the usb cdc connection bug of  temperature. and have update source code

**Comment by thomasgerman** [comment] 2019-08-22 13:59
Must i all uint_16 Switch to uint_8?
Or what?

Gesendet mit der WEB.DE iPhone App

Am 22.08.19 um 09:15 schrieb BigTreeTech

**Comment by reloxx13** [comment] 2019-08-23 07:00
> Must i all uint_16 Switch to uint_8? Or what? Gesendet mit der WEB.DE iPhone App Am 22.08.19 um 09:15 schrieb BigTreeTech
> […](#)
> look here [MarlinFirmware/Marlin#15026](https://github.com/MarlinFirmware/Marlin/pull/15026), we have fixed the usb cdc connection bug of temperature. and have update source code -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#2 (comment)](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3-/issues/2#issuecomment-523780953)

click on the link and read the changes.

**Comment by petrik0621** [comment] 2019-08-28 05:29
Hi. I need the Maple USB driver for the PC can anyone send me pls? I can't find it.

**Comment by Msq001** [comment] 2019-08-28 05:43
@petrik0621 https://github.com/bigtreetech/BIGTREETECH-SKR-MINI-V1.1/tree/master/firmware/mapleDrv-USBdriver

**Comment by petrik0621** [comment] 2019-08-28 05:49
@Msq001  thank, I found that too, but i don't know how to instal it :( I'm new

**Comment by Msq001** [comment] 2019-08-28 05:55
@petrik0621
1. first,  download this folder.
2. After you update the normal firmware, insert motherboard USB into PC, You should see a maple device with a yellow exclamation mark in the Device Manager
3. Right-click for Update Driver Software.
4. Select Browse PC Local Files for Update Driver
5. Select the folder has be download.
6. Start update driver...

**Comment by petrik0621** [comment] 2019-08-28 06:14
@Msq001 I can just open the folder, there is no download button.

Msq001 <notifications@github.com> ezt írta (időpont: 2019. aug. 28., Sze,
7:55):

**Comment by petrik0621** [comment] 2019-08-28 06:15
@Msq001 I can just open the folder, there is no download button.

**Comment by petrik0621** [comment] 2019-08-28 06:17
@Msq001 ![2](https://user-images.githubusercontent.com/54614650/63830342-34bd8f80-c96c-11e9-829b-bdaf8a35542b.jpg)
![1](https://user-images.githubusercontent.com/54614650/63830344-35562600-c96c-11e9-8eb2-57d6b484cf96.jpg)

**Comment by Msq001** [comment] 2019-08-28 06:22
I upload folder in here too https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3-/tree/master/firmware .
you can download the Whole repo
![image](https://user-images.githubusercontent.com/25599056/63830637-39e80200-c99f-11e9-89af-6311f856a891.png)

**Comment by petrik0621** [comment] 2019-08-28 06:34
@Msq001 ok thanks but what now?
I have Windows 8 :(
![3](https://user-images.githubusercontent.com/54614650/63831215-6e8f9580-c96e-11e9-89f6-fbf65c12fc6c.jpg)

**Comment by reloxx13** [comment] 2019-08-28 06:35
google "windows 8 install driver without digital signature"

**Comment by reloxx13** [comment] 2019-08-28 06:38
@bigtreetech u can close this now

**Closed** 2019-09-07 01:47 UTC

**Comment by Silversurfer79** [comment] 2019-11-29 00:30
Maybe a silly question, is there a bin file that i can load from SD or do i need have the SKR connect via USB to Adr or a PC to do this?

**Comment by Silversurfer79** [comment] 2019-12-01 15:26
?

**Comment by NotNiki** [comment] 2020-05-22 15:02
Hi, I connect the USB to a pc/octoprint it works but when i sent M305 for PID autotune my connection will always close and won't open again. Does anybody know what to do? Thanks, Adam.

**Comment by ajahongir** [comment] 2023-03-01 15:14
having problems with board. once as i flash with new firmware. i connect by usb and send **M501** **M500** to clear eeporm and save settins. make another minor changes and flash again but next time usb connection not working. its hang up when it try to connect by pronterface, all configurations are same. only i change offsets. i can not figure out why it stops to connect. tryed to reinstall firmware and so on. dont help is there any ideas? but when you connect. it recognize on PC.
